language: go

go:
  - 1.x

services:
  - docker

install:
  - ./backend/ci.sh install
  - ./frontend/ci.sh install
  - ./lambda_grades_fetcher/ci.sh install

script:
  - ./backend/ci.sh build
  - ./frontend/ci.sh build
  - ./lambda_grades_fetcher/ci.sh build

# sets the CNAME file so github continues serving canvascbl.com
before_deploy:
  - ./frontend/ci.sh before_deploy

deploy:
  - provider: script
    script: ./backend/ci.sh deploy && ./lambda_grades_fetcher/ci.sh deploy
    edge: true
    on:
      condition: $TRAVIS_BRANCH IN (master, staging)
  - provider: pages
    cleanup: false
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: bin/build
    committer_from_gh: true
    target_branch: gh-pages
    repo: iamtheyammer/canvascbl-stg
    edge: true
    on:
      branch: staging
  - provider: pages
    cleanup: false
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: bin/build
    committer_from_gh: true
    target_branch: gh-pages
    edge: true
    on:
      branch: master