language: go

go:
  - 1.x

before_install: cd frontend && nvm install `cat .nvmrc` && nvm use && cd ..

install: cd frontend && npm install && cd ..

script: make ci

# sets the CNAME file so github continues serving canvascbl.com
before_deploy: export REACT_APP_CURRENT_VERSION=`NODE_DISABLE_COLORS=1 node -e 'console.log(Date.now())'` && echo $CNAME > bin/build/CNAME

deploy:
  - provider: script
    script: bash deploy.sh $HEROKU_API_KEY $HEROKU_APP_NAME $HEROKU_PROCESS_NAME
    on:
      branch: containerize-backend
  - provider: pages
    cleanup: false
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: bin/build
    committer_from_gh: true
    target_branch: gh-pages
    repo: iamtheyammer/canvascbl-stg
    on:
       branch: staging
  - provider: pages
    cleanup: false
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: bin/build
    committer_from_gh: true
    target_branch: gh-pages
    on:
       branch: master
  edge: true