# CanvasCBL Master Travis Script

jobs:
  include:
    - stage: "Build Test"
      name: "Frontend"
      script:
        - ./frontend/ci.sh install
        - ./frontend/ci.sh build
    - script: ./backend/ci.sh install && ./backend/ci.sh build
      name: "Backend"
    - script: ./lambda_grades_fetcher/ci.sh install && ./lambda_grades_fetcher/ci.sh build
      name: "Lambda Grades Fetcher"
    - stage: "Deploy Backend and Lambda"
      if: branch IN (staging, master)
        - script: ./backend/ci.sh install && ./backend/ci.sh build && ./backend/ci.sh deploy
          name: "Backend"
        - script: ./lambda_grades_fetcher/ci.sh install && ./lambda_grades_fetcher/ci.sh build && ./lambda_grades_fetcher/ci.sh deploy
          name: "Lambda Grades Fetcher"
    - stage: "Deploy Frontend - Staging"
      if: branch = staging
      name: "Deploy Frontend to Staging"
      before_deploy: ./frontend/ci.sh install && ./frontend/ci.sh build && ./frontend/ci.sh before_deploy
      deploy:
        - provider: pages
          cleanup: false
          github_token: $GITHUB_TOKEN
          keep_history: false
          local_dir: bin/build
          committer_from_gh: true
          target_branch: gh-pages
          repo: iamtheyammer/canvascbl-stg
          edge: true
          on:
            branch: staging
    - stage: "Deploy Frontend - Production"
      if: branch = master
      name: "Deploy Frontend to Production"
      before_deploy: ./frontend/ci.sh install && ./frontend/ci.sh build && ./frontend/ci.sh before_deploy
      deploy:
        - provider: pages
          cleanup: false
          github_token: $GITHUB_TOKEN
          keep_history: false
          local_dir: bin/build
          committer_from_gh: true
          target_branch: gh-pages
          repo: iamtheyammer/canvascbl-stg
          edge: true

stages:
  - "Build Test"
  - "Deploy Backend and Lambda"
    if: branch IN (master, staging)
  - "Deploy Frontend - Staging"
    if: branch = staging
  - "Deploy Frontend - Production"
    if: branch = master