language: go

go:
  - 1.x

services:
  - docker

before_install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash # NVM
  - export NVM_DIR="$HOME/.nvm"
  - |
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
  - mkdir -p ~/aws/cli-install ~/aws/cli-files ~/aws/cli-bin
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o ~/aws/awscliv2.zip # AWS CLI
  - unzip ~/aws/awscliv2.zip -d ~/aws/cli-install > /dev/null
  - ~/aws/cli-install/aws/install --install-dir ~/aws/cli-files --bin-dir ~/aws/cli-bin
  - export PATH=$PATH:~/aws/cli-bin
  - aws --version

install:
  - ./backend/ci.sh install
  - ./frontend/ci.sh install
  - ./teacher_frontend/ci.sh install
  - ./account_frontend/ci.sh install
  - ./lambda_grades_fetcher/ci.sh install

script:
  - ./backend/ci.sh build
  - ./frontend/ci.sh build
  - ./teacher_frontend/ci.sh build
  - ./account_frontend/ci.sh build
  - ./lambda_grades_fetcher/ci.sh build

# sets the CNAME file so github continues serving canvascbl.com
before_deploy:
  - ./frontend/ci.sh before_deploy
  - ./teacher_frontend/ci.sh before_deploy
  - ./account_frontend/ci.sh before_deploy

deploy:
  - provider: script
    script: |
      ./backend/ci.sh deploy $HEROKU_API_KEY $HEROKU_APP_NAME $HEROKU_PROCESS_NAME &&
      ./lambda_grades_fetcher/ci.sh deploy $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $LAMBDA_GRADES_FETCHER_FUNCTION_NAME $TRAVIS_COMMIT &&
      ./frontend/ci.sh deploy $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $FRONTEND_S3_BUCKET_NAME &&
      ./teacher_frontend/ci.sh deploy $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $TEACHER_FRONTEND_S3_BUCKET_NAME &&
      ./account_frontend/ci.sh deploy $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $ACCOUNT_FRONTEND_S3_BUCKET_NAME
    edge: true
    on:
      branch: staging
  - provider: script
    script: |
      ./backend/ci.sh deploy $HEROKU_API_KEY $HEROKU_APP_NAME $HEROKU_PROCESS_NAME &&
      ./lambda_grades_fetcher/ci.sh deploy $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $LAMBDA_GRADES_FETCHER_FUNCTION_NAME $TRAVIS_COMMIT &&
      ./frontend/ci.sh deploy $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $FRONTEND_S3_BUCKET_NAME &&
      ./teacher_frontend/ci.sh deploy $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $TEACHER_FRONTEND_S3_BUCKET_NAME &&
      ./account_frontend/ci.sh deploy $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $ACCOUNT_FRONTEND_S3_BUCKET_NAME
    edge: true
    on:
      branch: master

      