language: go

go:
  - 1.x

services:
  - docker

install:
  - ./backend/ci.sh install
  - ./frontend/ci.sh install
  - ./teacher_frontend/ci.sh install
  - ./lambda_grades_fetcher/ci.sh install

script:
  - ./backend/ci.sh build
  - ./frontend/ci.sh build
  - ./teacher_frontend/ci.sh build
  - ./lambda_grades_fetcher/ci.sh build

# sets the CNAME file so github continues serving canvascbl.com
before_deploy:
  - ./frontend/ci.sh before_deploy
  - ./teacher_frontend/ci.sh before_deploy

deploy:
  - provider: script
    script: |
      ./backend/ci.sh deploy $HEROKU_API_KEY $HEROKU_APP_NAME $HEROKU_PROCESS_NAME &&
      ./lambda_grades_fetcher/ci.sh deploy $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $LAMBDA_GRADES_FETCHER_FUNCTION_NAME $TRAVIS_COMMIT
    edge: true
    on:
      branch: staging
  - provider: script
    script: |
      ./backend/ci.sh deploy $HEROKU_API_KEY $HEROKU_APP_NAME $HEROKU_PROCESS_NAME &&
      ./lambda_grades_fetcher/ci.sh deploy $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $LAMBDA_GRADES_FETCHER_FUNCTION_NAME $TRAVIS_COMMIT
    edge: true
    on:
      branch: master
  - provider: pages
    cleanup: false
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: frontend/build
    committer_from_gh: true
    target_branch: gh-pages
    repo: iamtheyammer/canvascbl-stg
    edge: true
    on:
      branch: staging
  - provider: pages
    cleanup: false
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: frontend/build
    committer_from_gh: true
    target_branch: gh-pages
    edge: true
    on:
      branch: master
  - provider: pages
    cleanup: false
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: teacher_frontend/build
    committer_from_gh: true
    target_branch: gh-pages
    repo: iamtheyammer/canvascbl-teacher-stg
    edge: true
    on:
      branch: staging
  - provider: pages
    cleanup: false
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: teacher_frontend/build
    committer_from_gh: true
    target_branch: gh-pages
    repo: iamtheyammer/canvascbl-teacher
    edge: true
    on:
      branch: master