name: Backend

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Set workdir
      run: |
        echo "::set-env name=WORKDIR::$GITHUB_WORKSPACE/backend"

    - name: Build
      run: |
        cd $WORKDIR
        go build -o bin/backend src/*.go

  deploy-prod:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: endsWith(github.ref, 'heads/master') || endsWith(github.ref, 'heads/staging')
    steps: 

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set workdir
      run: |
        echo "::set-env name=WORKDIR::$GITHUB_WORKSPACE/backend"

    - name: Set Heroku app name
      uses: iamtheyammer/branch-env-vars@v1.0.1
      with:
        HEROKU_APP_NAME: |
          master:${{ secrets.HEROKU_APP_NAME_PROD }}
          staging:${{ secrets.HEROKU_APP_NAME_STG }}

    - name: Build, deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        cd $WORKDIR
        heroku container:login
        heroku container:push web -a "$HEROKU_APP_NAME"
        heroku container:release web -a "$HEROKU_APP_NAME"
